repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: [--config=.codespellrc]

  - repo: local
    hooks:
      - id: whitelist-check
        name: Check whitelist is empty
        entry: python3
        language: system
        args: [-c, "exec(open('pcweb/whitelist.py').read()); assert not WHITELISTED_PAGES, f'WHITELISTED_PAGES includes {WHITELISTED_PAGES}'"]
        files: ^pcweb/whitelist\.py$
