on:
    workflow_dispatch: # Allow manual trigger
    push:
      branches: ['lendemor/use_deploy_action']

jobs:
    deploy-dev:
      runs-on: ubuntu-latest
      environment: DeployDev
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Deploy
          uses: reflex-dev/reflex-deploy-action@v1
          with:
            auth_token: ${{ secrets.REFLEX_AUTH_TOKEN }}
            project_id: ${{ secrets.PROJECT_ID }}
            extra_args: "--vm-type=${{ vars.VM_TYPE }}"
            dry_run: ${{ vars.DRY_RUN }}